namespace Euler.Problems.P2
{
    public class Solution : ISolution
    {
        private const int Limit = 4_000_000;
        public static string Solve()
        {
            /// <summary>
            /// https://projecteuler.net/problem=2
            ///
            /// Even Fibonacci Numbers
            ///
            /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with
            /// 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum
            /// of the even-valued terms.
            /// </summary>
            /// <remarks>
            /// Dunno why we're only considering even ones. It allows for an optimization, but hardly an important one.
            /// </remarks>
            int sum = 2;
            int oddFib1 = 3;
            int oddFib2 = 5;
            while (oddFib1 + oddFib2 <= Limit)
            {
                sum += oddFib1 + oddFib2;
                (oddFib1, oddFib2) = (oddFib1 + 2 * oddFib2, 2 * oddFib1 + 3 * oddFib2);
            }
            return sum.ToString();
        }
    }
}