"""
Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk  Pj| is minimised; what is the value of D?
"""

def gpi():
    i = 1
    while True:
        yield (i*(3*i-1))/2
        i += 1


def is_pent(n):
    mgpi = gpi()
    nextpent = mgpi.next()
    while nextpent <= n:
        if nextpent == n:
            return True
        nextpent = mgpi.next()
    return False

assert is_pent(1)
assert is_pent(5)
assert is_pent(12)
assert is_pent(22)
assert is_pent(35)
assert not is_pent(33)
assert not is_pent(7)

mgpi = gpi()
sgpi = gpi()
hgpi = gpi()
lower_pent = sgpi.next()
higher_pent = sgpi.next()
sum = hgpi.next()
for diff in mgpi:
    while higher_pent - lower_pent <= diff:
        if higher_pent - lower_pent == diff:
            while higher_pent + lower_pent >= sum:
                if higher_pent + lower_pent == sum:
                    print sum
                    exit(0)
                sum = hgpi.next()
        lower_pent = higher_pent
        higher_pent = sgpi.next()
