"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle         Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal         Pn=n(3n-1)/2         1, 5, 12, 22, 35, ...
Hexagonal         Hn=n(2n-1)         1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

types = ['T', 'P']


def get_triag_iterator():
    i = 285
    while True:
        i += 1
        yield (i*(i+1))/2

def get_pent_iterator():
    i = 165
    while True:
        i += 1
        yield (i*(3*i-1))/2

def get_hex_iterator():
    i = 143
    while True:
        i += 1
        yield i*(2*i-1)


tgen = get_triag_iterator()
pgen = get_pent_iterator()
hgen = get_hex_iterator()



hex = hgen.next()
triag = tgen.next()
triag = tgen.next()
pent = pgen.next()
while True:
    while pent < hex:
        pent = pgen.next()
    while triag < hex:
        triag = tgen.next()
    if pent == hex and triag == hex:
        print hex
        exit(0)
    hex = hgen.next()
