"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle         Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal         Pn=n(3n-1)/2         1, 5, 12, 22, 35, ...
Hexagonal         Hn=n(2n-1)         1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def triags(i=1):
    while True:
        yield (i*(i+1))/2
        i += 1

def pents(i=1):
    while True:
        yield (i*(3*i-1))/2
        i += 1

def hexs(i=1):
    while True:
        yield (i*(2*i-1))/2
        i += 1


tl = triags(285)
pl = pents(165)
hl = hexs(144)

t = tl.next()
p = pl.next()
h = hl.next()

while True:
    while t < h:
        t = tl.next()
    while p < h:
        p = pl.next()
    if p == t and t == h:
        print p
        exit()
    h = hl.next()